package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoorControl<M extends BaseDoorControl<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}

	public java.lang.String getNo() {
		return getStr("no");
	}

	public void setIsOpen(java.lang.Boolean isOpen) {
		set("is_open", isOpen);
	}

	public java.lang.Boolean getIsOpen() {
		return get("is_open");
	}

}
