package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMonitor<M extends BaseMonitor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCellId(java.lang.Integer cellId) {
		set("cell_id", cellId);
	}

	public java.lang.Integer getCellId() {
		return getInt("cell_id");
	}

	public void setFloor(java.lang.Integer floor) {
		set("floor", floor);
	}

	public java.lang.Integer getFloor() {
		return getInt("floor");
	}

}
