package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVisitor<M extends BaseVisitor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setIdCardId(java.lang.Long idCardId) {
		set("id_card_id", idCardId);
	}

	public java.lang.Long getIdCardId() {
		return getLong("id_card_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setNumberOfPeople(java.lang.Integer numberOfPeople) {
		set("number_of_people", numberOfPeople);
	}

	public java.lang.Integer getNumberOfPeople() {
		return getInt("number_of_people");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setMaster(java.lang.String master) {
		set("master", master);
	}

	public java.lang.String getMaster() {
		return getStr("master");
	}

	public void setIsAppointment(java.lang.Boolean isAppointment) {
		set("is_appointment", isAppointment);
	}

	public java.lang.Boolean getIsAppointment() {
		return get("is_appointment");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return getStr("reason");
	}

	public void setStartTime(java.lang.Integer startTime) {
		set("start_time", startTime);
	}

	public java.lang.Integer getStartTime() {
		return getInt("start_time");
	}

	public void setEndTime(java.lang.Integer endTime) {
		set("end_time", endTime);
	}

	public java.lang.Integer getEndTime() {
		return getInt("end_time");
	}

}
