package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdCard<M extends BaseIdCard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}

	public java.lang.String getNation() {
		return getStr("nation");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return getStr("number");
	}

	public void setIssue(java.lang.String issue) {
		set("issue", issue);
	}

	public java.lang.String getIssue() {
		return getStr("issue");
	}

	public void setEnableStartTime(java.util.Date enableStartTime) {
		set("enable_start_time", enableStartTime);
	}

	public java.util.Date getEnableStartTime() {
		return get("enable_start_time");
	}

	public void setEnableEndTime(java.util.Date enableEndTime) {
		set("enable_end_time", enableEndTime);
	}

	public java.util.Date getEnableEndTime() {
		return get("enable_end_time");
	}

	public void setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
	}

	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

}
