package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	public void setIsCommon(java.lang.Boolean isCommon) {
		set("is_common", isCommon);
	}

	public java.lang.Boolean getIsCommon() {
		return get("is_common");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
	}

	public java.lang.Boolean getIsShow() {
		return get("is_show");
	}

}
