package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCell<M extends BaseCell<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.Integer name) {
		set("name", name);
	}

	public java.lang.Integer getName() {
		return getInt("name");
	}

	public void setIsDraw(java.lang.Boolean isDraw) {
		set("is_draw", isDraw);
	}

	public java.lang.Boolean getIsDraw() {
		return get("is_draw");
	}

}
