package tpson.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return getInt("company_id");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setPaperType(java.lang.Integer paperType) {
		set("paper_type", paperType);
	}

	public java.lang.Integer getPaperType() {
		return getInt("paper_type");
	}

	public void setPaperNumber(java.lang.String paperNumber) {
		set("paper_number", paperNumber);
	}

	public java.lang.String getPaperNumber() {
		return getStr("paper_number");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}

	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public void setLoginTimes(java.lang.Integer loginTimes) {
		set("login_times", loginTimes);
	}

	public java.lang.Integer getLoginTimes() {
		return getInt("login_times");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return getStr("tel");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}

	public java.lang.String getTag() {
		return getStr("tag");
	}

	public void setDefaultSms(java.lang.Boolean defaultSms) {
		set("default_sms", defaultSms);
	}

	public java.lang.Boolean getDefaultSms() {
		return get("default_sms");
	}

	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	public java.lang.Long getAddTime() {
		return getLong("add_time");
	}

	public void setUpdateTime(java.lang.Long updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.Long getUpdateTime() {
		return getLong("update_time");
	}

	public void setDeleteTime(java.lang.Integer deleteTime) {
		set("delete_time", deleteTime);
	}

	public java.lang.Integer getDeleteTime() {
		return getInt("delete_time");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setIsDisable(java.lang.Boolean isDisable) {
		set("is_disable", isDisable);
	}

	public java.lang.Boolean getIsDisable() {
		return get("is_disable");
	}

}
