package tpson.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tp_building", "id", Building.class);
		arp.addMapping("tp_cell", "id", Cell.class);
		arp.addMapping("tp_door", "id", Door.class);
		arp.addMapping("tp_door_control", "id", DoorControl.class);
		arp.addMapping("tp_id_card", "id", IdCard.class);
		arp.addMapping("tp_monitor", "id", Monitor.class);
		arp.addMapping("tp_photo", "id", Photo.class);
		arp.addMapping("tp_resident", "id", Resident.class);
		arp.addMapping("tp_room", "id", Room.class);
		arp.addMapping("tp_user", "id", User.class);
		arp.addMapping("tp_user_action", "id", UserAction.class);
		arp.addMapping("tp_user_action_group", "id", UserActionGroup.class);
		arp.addMapping("tp_user_log", "id", UserLog.class);
		arp.addMapping("tp_user_role", "id", UserRole.class);
		arp.addMapping("tp_user_role_action", "id", UserRoleAction.class);
		arp.addMapping("tp_visitor", "id", Visitor.class);
	}
}

