package tpson.model;

import tpson.model.base.BaseCell;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cell extends BaseCell<Cell> {
	public static final Cell dao = new Cell().dao();
}
