package tpson.model;

import tpson.model.base.BaseDoor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Door extends BaseDoor<Door> {
	public static final Door dao = new Door().dao();
}
