package tpson.model;

import tpson.model.base.BaseDoorControl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoorControl extends BaseDoorControl<DoorControl> {
	public static final DoorControl dao = new DoorControl().dao();
}
