package tpson.model;

import tpson.model.base.BaseIdCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdCard extends BaseIdCard<IdCard> {
	public static final IdCard dao = new IdCard().dao();
}
