package tpson.model;

import tpson.model.base.BaseResident;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resident extends BaseResident<Resident> {
	public static final Resident dao = new Resident().dao();
}
