package tpson.model;

import tpson.model.base.BaseRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Room extends BaseRoom<Room> {
	public static final Room dao = new Room().dao();
}
