package tpson.model;

import com.jfinal.model.MergeConfig;
import com.jfinal.model.iAssociation;
import tpson.model.base.BaseUserActionGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserActionGroup extends BaseUserActionGroup<UserActionGroup> implements iAssociation {
	public static final UserActionGroup dao = new UserActionGroup().dao();

	@Override
	public MergeConfig association(String fk) {
		return new MergeConfig(fk).setAlias("name","action_group_name");
	}
}
