package tpson.model;

import tpson.model.base.BaseUserLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLog extends BaseUserLog<UserLog> {
	public static final UserLog dao = new UserLog().dao();
}
