package tpson.model;

import com.jfinal.kit.StrKit;
import com.jfinal.model.MergeConfig;
import com.jfinal.model.iAssociation;
import tpson.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> implements iAssociation {
	public static final User dao = new User().dao();

	public User findByName(String name){
		return dao.findFirst("select * from tp_user where username=?",name);
	}

	@Override
	public MergeConfig association(String fk) {
		fk = StrKit.isBlank(fk)?"user_id":fk;
		return new MergeConfig(fk)
				.setColumns("username");
	}
}
